import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;
import 'package:nekhna/src/operation.data.gql.dart'
    show
        GFetchIngredientsListData,
        GFetchIngredientsListData_ingredients,
        GFetchRecipeListData,
        GFetchRecipeListData_recipes,
        GFetchStepsListData,
        GFetchStepsListData_steps;
import 'package:nekhna/src/operation.req.gql.dart'
    show GFetchIngredientsListReq, GFetchRecipeListReq, GFetchStepsListReq;
import 'package:nekhna/src/operation.var.gql.dart'
    show GFetchIngredientsListVars, GFetchRecipeListVars, GFetchStepsListVars;
import 'package:nekhna/src/schema.schema.gql.dart'
    show
        GInt_comparison_exp,
        GString_comparison_exp,
        Gingredients_aggregate_order_by,
        Gingredients_arr_rel_insert_input,
        Gingredients_avg_order_by,
        Gingredients_bool_exp,
        Gingredients_constraint,
        Gingredients_inc_input,
        Gingredients_insert_input,
        Gingredients_max_order_by,
        Gingredients_min_order_by,
        Gingredients_on_conflict,
        Gingredients_order_by,
        Gingredients_pk_columns_input,
        Gingredients_select_column,
        Gingredients_set_input,
        Gingredients_stddev_order_by,
        Gingredients_stddev_pop_order_by,
        Gingredients_stddev_samp_order_by,
        Gingredients_sum_order_by,
        Gingredients_update_column,
        Gingredients_var_pop_order_by,
        Gingredients_var_samp_order_by,
        Gingredients_variance_order_by,
        Gorder_by,
        Grecipes_bool_exp,
        Grecipes_constraint,
        Grecipes_inc_input,
        Grecipes_insert_input,
        Grecipes_obj_rel_insert_input,
        Grecipes_on_conflict,
        Grecipes_order_by,
        Grecipes_pk_columns_input,
        Grecipes_select_column,
        Grecipes_set_input,
        Grecipes_update_column,
        Gsteps_aggregate_order_by,
        Gsteps_arr_rel_insert_input,
        Gsteps_avg_order_by,
        Gsteps_bool_exp,
        Gsteps_constraint,
        Gsteps_inc_input,
        Gsteps_insert_input,
        Gsteps_max_order_by,
        Gsteps_min_order_by,
        Gsteps_on_conflict,
        Gsteps_order_by,
        Gsteps_pk_columns_input,
        Gsteps_select_column,
        Gsteps_set_input,
        Gsteps_stddev_order_by,
        Gsteps_stddev_pop_order_by,
        Gsteps_stddev_samp_order_by,
        Gsteps_sum_order_by,
        Gsteps_update_column,
        Gsteps_var_pop_order_by,
        Gsteps_var_samp_order_by,
        Gsteps_variance_order_by;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GFetchIngredientsListData,
  GFetchIngredientsListData_ingredients,
  GFetchIngredientsListReq,
  GFetchIngredientsListVars,
  GFetchRecipeListData,
  GFetchRecipeListData_recipes,
  GFetchRecipeListReq,
  GFetchRecipeListVars,
  GFetchStepsListData,
  GFetchStepsListData_steps,
  GFetchStepsListReq,
  GFetchStepsListVars,
  GInt_comparison_exp,
  GString_comparison_exp,
  Gingredients_aggregate_order_by,
  Gingredients_arr_rel_insert_input,
  Gingredients_avg_order_by,
  Gingredients_bool_exp,
  Gingredients_constraint,
  Gingredients_inc_input,
  Gingredients_insert_input,
  Gingredients_max_order_by,
  Gingredients_min_order_by,
  Gingredients_on_conflict,
  Gingredients_order_by,
  Gingredients_pk_columns_input,
  Gingredients_select_column,
  Gingredients_set_input,
  Gingredients_stddev_order_by,
  Gingredients_stddev_pop_order_by,
  Gingredients_stddev_samp_order_by,
  Gingredients_sum_order_by,
  Gingredients_update_column,
  Gingredients_var_pop_order_by,
  Gingredients_var_samp_order_by,
  Gingredients_variance_order_by,
  Gorder_by,
  Grecipes_bool_exp,
  Grecipes_constraint,
  Grecipes_inc_input,
  Grecipes_insert_input,
  Grecipes_obj_rel_insert_input,
  Grecipes_on_conflict,
  Grecipes_order_by,
  Grecipes_pk_columns_input,
  Grecipes_select_column,
  Grecipes_set_input,
  Grecipes_update_column,
  Gsteps_aggregate_order_by,
  Gsteps_arr_rel_insert_input,
  Gsteps_avg_order_by,
  Gsteps_bool_exp,
  Gsteps_constraint,
  Gsteps_inc_input,
  Gsteps_insert_input,
  Gsteps_max_order_by,
  Gsteps_min_order_by,
  Gsteps_on_conflict,
  Gsteps_order_by,
  Gsteps_pk_columns_input,
  Gsteps_select_column,
  Gsteps_set_input,
  Gsteps_stddev_order_by,
  Gsteps_stddev_pop_order_by,
  Gsteps_stddev_samp_order_by,
  Gsteps_sum_order_by,
  Gsteps_update_column,
  Gsteps_var_pop_order_by,
  Gsteps_var_samp_order_by,
  Gsteps_variance_order_by
])
final Serializers serializers = _serializersBuilder.build();
